sudo: required
services:
  - docker
language: go
go:
  - "1.11"
env:
  - GO111MODULE=on
jobs:
  include:
    - stage: build
      script: make build
    - stage: deploy
      if: branch = master
      script: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin && make push
