sudo: required
services:
  - docker
  - mongodb
language: go
go:
  - "1.11"
env:
  - GO111MODULE=on
script:
  - export BRANCH=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo
    $TRAVIS_BRANCH; else echo $TRAVIS_PULL_REQUEST_BRANCH; fi)
  - echo "TRAVIS_BRANCH=$TRAVIS_BRANCH, PR=$PR, BRANCH=$BRANCH"
  - make static
  - make test
  - test $BRANCH = master && echo "$DOCKER_PASSWORD" | docker login -u
    "$DOCKER_USERNAME" --password-stdin && make build && make push
