sudo: required
services:
  - docker
language: go
go:
  - "1.11"
env:
  - GO111MODULE=on
script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME"
    --password-stdin
  - make build
  - make push
branches:
  only:
    - master
